### ISSUE TITLE
Quotes not escaped in calendar

### ISSUE THREAD

**Issue by GideonWolfe** [rayes0/dotfiles#3]
I'm implementing your calendar, and I seem to be getting the raw `&quot` from the `eww.xml` file

![image](https://user-images.githubusercontent.com/32942052/113215902-6a091e00-9230-11eb-8ba4-1ba149a5cf5f.png)

Removing the `&quot;` shows the quote without the `"`, but I'm not sure why it's happening in the first place, since it should just insert a `"`.

**Comment by rayes0** [comment]
This is a known issue with roxml in eww. As a temporary fix, use an eww version _before_ [this commit](https://github.com/elkowar/eww/commit/a18901f187ff850a21a24c0c59022c0a5382ffd9), so use [this version](https://github.com/elkowar/eww/commit/6251a2bc1d6ef31b3fb06e6bad41587940c0673b). My configs will work with those as they don't use any of the newer features of eww.

XML and GTK are both bad with double quotes to begin with. Eww is planning on upgrading the syntax of their config, which should fix this. Until then, there's really nothing to be done except use an older version (unfortunately).

You could of course opt for just not using the double quotes, and still use newer versions of eww if you wish.

**Comment by GideonWolfe** [comment]
Ah gotcha. I'll probably just remove the quotes then. I would have never figured that out on my own, thanks!
