### ISSUE TITLE
Calendar not respecting width

### ISSUE THREAD

**Issue by GideonWolfe** [rayes0/dotfiles#4]
I doubt this is a bug with your config specifically, but I'm struggling to understand the "rules" for breaking the quote.

For example in this screenshot, I have highlighted where i have the width of the `calendar` window set to `20%`.

![image](https://user-images.githubusercontent.com/32942052/113235826-9fc1fd00-9258-11eb-8dcc-05a206e15426.png)

But as you can see, it's far wider than that. I *have* seen instances of long quotes being broken into multiple lines, but only after the entire width of my screen is used up. I tried setting a `max-width` property in `eww.scss` but it didn't like that.

Ideally the proportions would be similar to how you have it, with the quote taking a few lines up if necessary.

**Comment by rayes0** [comment]
This is another known issue with the GTK implementation in `eww`. The `limit-width` property currently does not work. Unfortunately, there's not much we can do right now about it right now until `eww` makes some changes :(

**Comment by GideonWolfe** [comment]
Ah gotcha! Yeah the behavior is quite strange. Like sometimes it will render a quote on two lines while taking up like 60% width (like above) and then it rill **re-render** as i'm looking at it to take up the full screen width. As long as it isn't a problem with my config, I'm fine with waiting for the upstream fix. `eww` is super cool but obviously new, there's **very** few decent examples to work from 😂
