### ISSUE TITLE
EWW Todo Question.

### ISSUE THREAD

**Issue by ramaxpublic** [rayes0/dotfiles#6]
in eww config, there is a check-todo.sh script and it has `todo="$(todo.sh list | head -n -2 | sed -e '/[0-9]\+[[:blank:]]x/d' -e 's/\x1B\[[0-9;]*[JKmsu]//g;/. x 2/d')"` where i can get the `todo.sh` ? and how do they work? what should i have if i want to have todo widgets?

**Comment by rayes0** [comment]
The todo script is from the [todo.txt cli](https://github.com/todotxt/todo.txt-cli).

I got rid of the old documentation for setting up widgets. I don't use eww anymore, and the setup I previously had was pretty niche and hacky. You can view the [old readme with instructions](https://github.com/rayes0/dotfiles/tree/186ccaa50594a62c92998bd9e42c173b96c75481) in the commit history if you want to try setting it up.

-------- Original Message --------

**Comment by ramaxpublic** [comment]
Thanks! i'll do what you have `suggested.`
